version : "3"

services :
   zookeeper:
     image: wurstmeister/zookeeper
     container_name :  zookeeper
     ports:
       - "2181:2181"

   broker:
     image: wurstmeister/kafka
     container_name :  broker
     ports:
       - "9092:9092"
     environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "twitterstream:1:1"

   mongodb:
     image: mongo:5.0
     ports:
       - 27017:27017
     volumes:
        - "./mongo/data:/data/db"






